version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superpswd

    volumes: 
          # copy the sql script to create tables
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
